# Ass5
## GUO PEIHONG

In [94]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [96]:
df = pd.read_csv('/content/drive/MyDrive/BS6204&08/HW4data.csv')
df

Unnamed: 0   sample_0   sample_1   sample_2   sample_3  \
0           ?|100130426   0.000000   0.000000   0.000000   0.000000   
1           ?|100133144   2.017209   0.592732   3.511759   3.663618   
2           ?|100134869   3.265527   1.588421   4.327199   4.507649   
3               ?|10357   5.478487   7.586157   6.881787   6.659068   
4               ?|10431  10.431999   9.623011   9.870730  10.196184   
...                 ...        ...        ...        ...        ...   
20526          ZYX|7791  12.003135  12.674552   9.045255  11.392682   
20527       ZZEF1|23140   9.650743  10.517059   9.788359   9.694814   
20528        ZZZ3|26009   8.921326   9.397854  10.090470   9.684365   
20529  psiTPTE22|387590   5.286759   2.094168   1.683023   3.292001   
20530       tAKR|389932   0.000000   0.000000   0.000000   0.000000   

        sample_4   sample_5   sample_6   sample_7   sample_8  ...  sample_791  \
0       0.000000   0.000000   0.000000   0.000000   0.000000  ...    0.000000   
1       2.655741   3.467853   1.224966   2.854853   3.992125  ...    3.080061   
2       2.821547   3.581918   1.691177   1.750478   2.772730  ...    2.815739   
3       6.539454   6.620243   6.572007   7.226720   6.546692  ...    6.209617   
4       9.738265   9.706829   9.640511   9.758691  10.488252  ...    9.644469   
...          ...        ...        ...        ...        ...  ...         ...   
20526  11.922439  11.556995  13.256060  12.670377  12.498919  ...   11.035335   
20527   9.217749   9.244150   9.664486   9.987733  10.389954  ...   11.030377   
20528   9.461191   9.836473   9.244219   9.216872  10.390255  ...   10.119304   
20529   5.110372   5.355133   8.330912   6.551490   7.828321  ...    7.313500   
20530   0.000000   0.000000   0.000000   0.000000   0.000000  ...    0.000000   

       sample_792  sample_793  sample_794  sample_795  sample_796  sample_797  \
0        0.000000    0.000000    0.000000    0.436588    0.000000    0.000000   
1        4.337404    2.068224    4.288388    4.472176    1.865642    3.942955   
2        2.597126    0.857663    3.452490    4.908746    2.718197    4.453807   
3        6.070379    6.218739    7.209151    5.937848    7.350099    6.346597   
4        9.863990   10.623068    9.875620    9.330901   10.006003   10.056868   
...           ...         ...         ...         ...         ...         ...   
20526   10.864960   10.703722   10.790014   10.961247   12.031267   11.633422   
20527    9.617853    9.144204   10.698991   10.203226    9.813063   10.317266   
20528   12.813320    9.682057   10.081523   10.030005   10.092770    8.745983   
20529    3.805261    5.384968    4.376693    3.675703    8.819269    9.659081   
20530    0.000000    0.789354    0.000000    0.000000    0.000000    0.000000   

       sample_798  sample_799  sample_800  
0        0.000000    0.000000    0.000000  
1        3.249582    2.590339    2.325242  
2        3.707492    2.787976    3.805932  
3        8.185901    7.318624    6.530246  
4        9.504082    9.987136    9.560367  
...           ...         ...         ...  
20526   12.180944   11.198279   11.641081  
20527   10.681194   10.335513   10.607358  
20528    9.466711   10.400581    9.844794  
20529    4.677458    5.718751    4.550716  
20530    0.586693    0.000000    0.000000  

[20531 rows x 802 columns]

In [97]:
data_drop = df.drop(['Unnamed: 0'],axis=1)

In [98]:
data_drop['var'] = 0.0
for i in range(0, 20531):
    data_drop['var'][i] = np.var(data_drop.iloc[i])

Remove genes that have low variance across the dataset(flat genes ). This is to reduce the amount of data and not to affect the final prediction results. I chose to take the cutoff=6 in assignment4

In [99]:
data = data_drop[data_drop['var'] > 6]
data = data.drop(['var'],axis=1)
data = data.T

In [100]:
data

18        26        30         33        61        62     \
sample_0    0.591871  7.215116  0.000000   4.747656  1.010279  0.000000   
sample_1    0.000000  9.949812  0.000000   1.327170  3.499846  3.866146   
sample_2    1.683023  6.096650  0.000000   0.000000  1.683023  0.452595   
sample_3    1.267356  3.913761  0.000000   7.742714  1.637239  0.000000   
sample_4    0.889707  1.942120  0.000000   2.612801  8.930616  1.711142   
...              ...       ...       ...        ...       ...       ...   
sample_796  0.496922  0.000000  0.000000   0.865919  4.814632  0.000000   
sample_797  0.000000  9.169589  0.000000   2.245891  8.140998  4.377547   
sample_798  1.002595  1.325099  6.831738   5.574986  6.103195  2.589332   
sample_799  0.000000  3.450934  0.581881   2.451778  0.581881  1.578746   
sample_800  0.000000  3.485246  0.748375  10.319525  3.195174  0.748375   

               67        71         83        87     ...      19661     19760  \
sample_0    3.478079  7.377931  10.796510  0.591871  ...   1.094912  7.134098   
sample_1    8.605872  4.312113   2.176738  4.927347  ...  11.169775  5.227706   
sample_2    2.533663  1.683023   2.785739  5.199433  ...   0.000000  7.766025   
sample_3    1.464093  4.949633   9.634793  3.006442  ...   1.031960  8.804357   
sample_4    4.778072  5.133921  10.337165  3.252204  ...  12.783131  3.252204   
...              ...       ...        ...       ...  ...        ...       ...   
sample_796  1.955573  6.448896   7.281930  0.496922  ...  12.387045  3.737373   
sample_797  4.449931  4.301339   2.666211  3.409486  ...   1.784043  2.782912   
sample_798  3.759742  7.185113   1.002595  7.822201  ...   3.762944  6.185076   
sample_799  1.578746  8.545266   1.316320  0.581881  ...   3.687374  9.781012   
sample_800  3.650581  7.194757  10.339338  2.963308  ...   0.748375  7.771958   

               19913      19914     19921     19922     19937      20125  \
sample_0    7.475709  11.919474  1.010279  1.598651  3.478079   7.118380   
sample_1    0.323658   4.095722  6.656145  5.275331  0.000000   6.915593   
sample_2    8.276897   9.526732  0.000000  1.839758  0.796598   4.683084   
sample_3    8.550566  11.807347  0.000000  6.135506  1.931418  10.435608   
sample_4    0.000000  11.542147  2.544139  4.461804  5.122192   3.414853   
...              ...        ...       ...       ...       ...        ...   
sample_796  0.000000  11.590989  3.905158  0.000000  1.955573   4.561815   
sample_797  8.740584   8.264053  0.000000  0.000000  7.768925   6.658211   
sample_798  7.993906   5.431382  3.252612  9.915126  4.619736   5.559718   
sample_799  7.623699  10.586380  0.000000  4.035615  4.605743   7.056811   
sample_800  6.331798  10.286130  0.000000  6.403075  0.000000   3.933393   

               20389     20476  
sample_0    7.360224  9.175285  
sample_1    2.814879  0.000000  
sample_2    4.306933  8.834108  
sample_3    7.728424  7.529188  
sample_4    6.171291  7.647883  
...              ...       ...  
sample_796  6.114061  8.486940  
sample_797  7.789997  8.207756  
sample_798  6.559773  8.089895  
sample_799  5.810998  7.605413  
sample_800  4.709103  8.148944  

[801 rows x 1174 columns]

In [101]:
da = df.drop(['Unnamed: 0'],axis=1)
da['var'] = 0.0
for i in range(0, 20531):
    da['var'][i] = np.var(da.iloc[i])
    
da["name"] = df['Unnamed: 0']
da_i = da[da['var'] > 6]

In [102]:
da_i.head()

sample_0  sample_1  sample_2  sample_3  sample_4  sample_5  sample_6  \
18  0.591871  0.000000  1.683023  1.267356  0.889707  0.894294  9.466878   
26  7.215116  9.949812  6.096650  3.913761  1.942120  0.894294  0.000000   
30  0.000000  0.000000  0.000000  0.000000  0.000000  4.936704  0.000000   
33  4.747656  1.327170  0.000000  7.742714  2.612801  2.002018  0.000000   
61  1.010279  3.499846  1.683023  1.637239  8.930616  0.515410  2.042924   

    sample_7  sample_8  sample_9  ...  sample_793  sample_794  sample_795  \
18  0.000000  0.635336  0.000000  ...    0.789354    0.416948    6.541532   
26  5.145527  6.080374  0.724214  ...    1.496104    2.228542    2.041944   
30  0.000000  0.000000  0.000000  ...    0.000000    0.000000    0.000000   
33  5.145527  9.464329  0.000000  ...    2.424922    3.176897    3.272173   
61  0.441802  6.919519  4.057268  ...    6.423758    0.740107   11.408584   

    sample_796  sample_797  sample_798  sample_799  sample_800        var  \
18    0.496922    0.000000    1.002595    0.000000    0.000000  10.188473   
26    0.000000    9.169589    1.325099    3.450934    3.485246   7.105668   
30    0.000000    0.000000    6.831738    0.581881    0.748375   9.971340   
33    0.865919    2.245891    5.574986    2.451778   10.319525   7.392214   
61    4.814632    8.140998    6.103195    0.581881    3.195174  10.640432   

            name  
18      ?|553137  
26      ?|729884  
30    A1CF|29974  
33  A2ML1|144568  
61  ABCA12|26154  

[5 rows x 803 columns]

## Random Forest

In [103]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, silhouette_score, matthews_corrcoef

In [104]:
labels = pd.read_csv("/content/drive/MyDrive/BS6204&08/HW4labels.csv")

### PRAD

In [105]:
color = list(labels['Class'])
c = {'PRAD':1, 'LUAD':0, 'BRCA':0, 'KIRC':0, 'COAD':0}
for i in range(len(color)):
    color[i] = c[color[i]]
X = data
y = color

In [106]:
rf = RandomForestClassifier(max_features="auto", random_state=123, oob_score=True)
rf.fit(X, y)
rf_pred = rf.oob_decision_function_

In [107]:
y_pred = []
for i in range(len(rf_pred)):
    position = list(rf_pred[i]).index(max(list(rf_pred[i])))
    y_pred.append(position)

print('\nMCC: %f' % (matthews_corrcoef(y, y_pred)))
confusion_matrix(y, y_pred)


MCC: 0.995568


array([[665,   0],
       [  1, 135]])

In [108]:
importance = pd.DataFrame()
importance["index"] = list(da_i['name'])
importance["importance"] = list(rf.feature_importances_)
importance.sort_values(by="importance", ascending=False).head()

index  importance
219     CHRNA2|1135    0.052154
755    OR51E2|81285    0.044016
972   SLC45A3|85414    0.042817
518    HOXB13|10481    0.041844
1044    TARP|445347    0.037839

In [109]:
ls = importance.sort_values(by="importance", ascending=False)["index"][:20].to_list()
for i in ls:
    print(i.split("|")[0])

CHRNA2
OR51E2
SLC45A3
HOXB13
TARP
GDEP
KLK3
BEND4
KLK4
KLKP1
TMEFF2
CUX2
NKX3-1
LMAN1L
C17orf93
KLK2
PABPC1L2B
TMPRSS2
FEV
TRPM8


### LUAD

In [110]:
color = list(labels['Class'])
c = {'PRAD':0, 'LUAD':1, 'BRCA':0, 'KIRC':0, 'COAD':0}
for i in range(len(color)):
    color[i] = c[color[i]]   
x = data
y = color

In [111]:
rf = RandomForestClassifier(max_features="auto", random_state=123, oob_score=True)
rf.fit(X, y)
rf_pred = rf.oob_decision_function_

In [112]:
y_pred = []
for i in range(len(rf_pred)):
    position = list(rf_pred[i]).index(max(list(rf_pred[i])))
    y_pred.append(position)

print('\nMCC: %f' % (matthews_corrcoef(y, y_pred)))
confusion_matrix(y, y_pred)


MCC: 0.982740


array([[660,   0],
       [  4, 137]])

In [113]:
importance = pd.DataFrame()
importance["index"] = list(da_i['name'])
importance["importance"] = list(rf.feature_importances_)
importance.sort_values(by="importance", ascending=False).head()

index  importance
929  SFTA3|253970    0.055685
702  MUC21|394263    0.046051
928  SFTA2|389376    0.043745
933    SFTPC|6440    0.043430
755  OR51E2|81285    0.041471

In [114]:
ls = importance.sort_values(by="importance", ascending=False)["index"][:20].to_list()
for i in ls:
    print(i.split("|")[0])

SFTA3
MUC21
SFTA2
SFTPC
OR51E2
SCEL
ROS1
C4BPA
CHIA
CTSE
XAGE1D
SCGB3A2
PON3
SFTPB
BMP3
SLC34A2
SFTA1P
LMO3
SFTPD
NKX2-1


### BRCA

In [115]:
color = list(labels['Class'])
c = {'PRAD':0, 'LUAD':0, 'BRCA':1, 'KIRC':0, 'COAD':0}
for i in range(len(color)):
    color[i] = c[color[i]]
    
x = data
y = color

In [116]:
rf = RandomForestClassifier(max_features="auto", random_state=123, oob_score=True)
rf.fit(X, y)
rf_pred = rf.oob_decision_function_

In [117]:
y_pred = []
for i in range(len(rf_pred)):
    position = list(rf_pred[i]).index(max(list(rf_pred[i])))
    y_pred.append(position)

print('\nMCC: %f' % (matthews_corrcoef(y, y_pred)))
confusion_matrix(y, y_pred)


MCC: 0.997337


array([[501,   0],
       [  1, 299]])

In [118]:
importance = pd.DataFrame()
importance["index"] = list(da_i['name'])
importance["importance"] = list(rf.feature_importances_)
importance.sort_values(by="importance", ascending=False).head()

index  importance
441       GATA3|2625    0.053054
1112      TRPS1|7227    0.050046
365         EN1|2019    0.041054
157   C8orf85|441376    0.035582
507       HNF1B|6928    0.034942

In [119]:
ls = importance.sort_values(by="importance", ascending=False)["index"][:20].to_list()
for i in ls:
    print(i.split("|")[0] )

GATA3
TRPS1
EN1
C8orf85
HNF1B
LMX1B
TFAP2A
EFHD1
C11orf41
THRSP
SLC22A3
SHH
PRLR
FLJ45983
TCF21
IL20
SCGB2A2
NR1H4
UTY
SYCP2


### KIRC

In [120]:
color = list(labels['Class'])
c = {'PRAD':0, 'LUAD':0, 'BRCA':0, 'KIRC':1, 'COAD':0}
for i in range(len(color)):
  color[i] = c[color[i]]
    
x = data
y = color

In [121]:
rf = RandomForestClassifier(max_features="auto", random_state=123, oob_score=True)
rf.fit(X, y)
rf_pred = rf.oob_decision_function_

In [122]:
y_pred = []
for i in range(len(rf_pred)):
    position = list(rf_pred[i]).index(max(list(rf_pred[i])))
    y_pred.append(position)

print('\nMCC: %f' % (matthews_corrcoef(y, y_pred)))
confusion_matrix(y, y_pred)


MCC: 0.995810


array([[655,   0],
       [  1, 145]])

In [123]:
importance = pd.DataFrame()
importance["index"] = list(da_i['name'])
importance["importance"] = list(rf.feature_importances_)
importance.sort_values(by="importance", ascending=False).head()

index  importance
842            PRODH2|58510    0.048858
21              ACSM5|54988    0.048039
624  LOC100131551|100131551    0.036897
137        C20orf151|140893    0.029550
825             POU3F3|5455    0.029122

In [124]:
ls = importance.sort_values(by="importance", ascending=False)["index"][:20].to_list()
for i in ls:
    print(i.split("|")[0] )

PRODH2
ACSM5
LOC100131551
C20orf151
POU3F3
BHMT
GPX3
GRHL2
PRSS22
GLYAT
SLC22A2
ALPK2
NAT8
C14orf105
IGSF9
ACSM2B
OVOL2
NR1H4
CDH6
SLC6A13


### COAD

In [125]:
color = list(labels['Class'])
c = {'PRAD':0, 'LUAD':0, 'BRCA':0, 'KIRC':0, 'COAD':1}
for i in range(len(color)):
    color[i] = c[color[i]]
    
x = data
y = color

In [126]:
rf = RandomForestClassifier(max_features="auto", random_state=123, oob_score=True)
rf.fit(X, y)
rf_pred = rf.oob_decision_function_

In [127]:
y_pred = []
for i in range(len(rf_pred)):
    position = list(rf_pred[i]).index(max(list(rf_pred[i])))
    y_pred.append(position)

print('\nMCC: %f' % (matthews_corrcoef(y, y_pred)))
confusion_matrix(y, y_pred)


MCC: 0.985734


array([[723,   0],
       [  2,  76]])

In [128]:
importance = pd.DataFrame()
importance["index"] = list(da_i['name'])
importance["importance"] = list(rf.feature_importances_)
importance.sort_values(by="importance", ascending=False).head()

index  importance
850   PRSS3|5646    0.052773
823  POF1B|79983    0.048506
615  LGALS4|3960    0.038673
462  GPA33|10223    0.034656
200    CDX1|1044    0.033541

In [129]:
ls = importance.sort_values(by="importance", ascending=False)["index"][:20].to_list()
for i in ls:
    print(i.split("|")[0])

PRSS3
POF1B
LGALS4
GPA33
CDX1
MYO7B
ATP10B
KRT20
CDX2
CFTR
ERN2
GUCY2C
MEP1A
CDH17
NR1I2
FERMT1
PHGR1
VIL1
FABP1
IL22RA1
